### ISSUE TITLE
Lab 2 results

### ISSUE THREAD

**Issue by svayamm** [iOS-updates-2018/Labs#3]
### Errors

Part 1 Step 7: 

> dismissViewControllerAnimated(_:completion:)' has been renamed to 'dismiss(animated:completion:)'

Part 1 Step 10: 

> Instance method 'textFieldShouldReturn(textField:)' nearly matches optional requirement 'textFieldShouldReturn' of protocol 'UITextFieldDelegate' 

-- method argument name needed to be changed, apparently.

##### Queue playground:

- Line 15: `array` should be public (as it is in Stacks playground) instead of private
- Line 50: `enqueue` missing argument label `element:`

### Misc.

Stacks Step 2: _'Change on the the tests'_ to _'Change one of the tests'_
Queues Step 2: _'check out'_ to _'refer to'_

Possibly add more screenshots in Step 1
Also, I'm not entirely sure what the `updateDisplay` function does in Step 1, since I don't think I filled it in but my app still works fine (and I excluded it entirely when I'd done it for the lab way back when)

### Timing

Part 1: 58:19

Part 2: **Overall** - 16:44
_Stacks_ - 3:32
Stacks Playground - 2:49
StacksTests - 0:43

_Queues_ - 13:12
Queues Playground - 4:30
QueuesTests - 8:42

**Comment by liao-frank** [comment]
## Errors
*Part 1 Step 7*
dismissViewControllerAnimated(_:completion:)' has been renamed to 'dismiss(animated:completion:)'
*Stacks Step 2*
"Change on the the tests"
*Queues Playground*
Missing argument label
The informal tests assume that `array` is a public attribute

## Suggestion
- Put the TimeConverter skeleton with the instructions. The rest of the steps are based on the specific design of TimeConverter, so the expected design could be more transparent.
- Part 1 Step 5: The `let foo = Int(input.text!)` covers the first case check of checking for `""`.
- Part 1 Step 7: Direction on changing button to "info-light"
- Part 1 Step 8: My view had no Lorem ipsum default text
- Part 1 Step 9/10: I don't have an iPhone. But I was able to bring up the keyboard on the emulator at one point. Perhaps this could be looked into.

## Timing
Part 1: 64:05

Part 2: 
Stacks - 3:46
Playground - 2:56
Testing - 0:50

Queues - 7:26
Playground - 2:45
Testing - 4:41
